### ISSUE TITLE
torch_shm_manager: error while loading shared libraries: libcudart.so.10.1: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by x-zho14** [allenai/hidden-networks#3]
python main.py --config configs/smallscale/conv4/conv4_usc_unsigned.yml                --multigpu 8                --name example                --data  dataset/                --prune-rate 0.5

Run with this command, with the requirements installed and cuda 10.1, I encounter this error when running. Could you help me? Thank you very much!

> => Reading YAML config from configs/smallscale/conv4/conv4_usc_unsigned.yml
> Namespace(arch='Conv4', batch_size=128, bn_type='NonAffineBatchNorm', config='configs/smallscale/conv4/conv4_usc_unsigned.yml', conv_type='SubnetConv', data='dataset/', epochs=100, evaluate=False, first_layer_dense=False, first_layer_type=None, freeze_weights=True, init='signed_constant', label_smoothing=None, last_layer_dense=False, log_dir=None, low_data=1, lr=0.1, lr_policy='cosine_lr', mode='fan_in', momentum=0.9, multigpu=[8], multistep_lr_adjust=30, multistep_lr_gamma=0.1, name='example', nesterov=False, no_bn_decay=False, nonlinearity='relu', num_classes=10, one_batch=False, optimizer='sgd', pretrained=None, print_freq=10, prune_rate=0.5, random_subnet=False, resume='', save_every=-1, scale_fan=False, score_init_constant=None, seed=None, set='CIFAR10', start_epoch=None, trainer='default', warmup_length=0, weight_decay=0.0001, width_mult=1.0, workers=4)
> => Using trainer from trainers.default
> => Creating model 'Conv4'
> ==> Conv Type: SubnetConv
> ==> BN Type: NonAffineBatchNorm
> ==> Building first layer with <class 'utils.conv_type.SubnetConv'>
> ==> Setting prune rate of network to 0.5
> ==> Setting prune rate of convs.0 to 0.5
> ==> Setting prune rate of convs.2 to 0.5
> ==> Setting prune rate of convs.5 to 0.5
> ==> Setting prune rate of convs.7 to 0.5
> ==> Setting prune rate of linear.0 to 0.5
> ==> Setting prune rate of linear.2 to 0.5
> ==> Setting prune rate of linear.4 to 0.5
> => Rough estimate model params 1212512
> => Freezing model weights
> ==> No gradient to convs.0.weight
> ==> No gradient to convs.2.weight
> ==> No gradient to convs.5.weight
> ==> No gradient to convs.7.weight
> ==> No gradient to linear.0.weight
> ==> No gradient to linear.2.weight
> ==> No gradient to linear.4.weight
> => Parallelizing on [8] gpus
> <DEBUG> no gradient to module.convs.0.weight
> <DEBUG> gradient to module.convs.0.scores
> <DEBUG> no gradient to module.convs.2.weight
> <DEBUG> gradient to module.convs.2.scores
> <DEBUG> no gradient to module.convs.5.weight
> <DEBUG> gradient to module.convs.5.scores
> <DEBUG> no gradient to module.convs.7.weight
> <DEBUG> gradient to module.convs.7.scores
> <DEBUG> no gradient to module.linear.0.weight
> <DEBUG> gradient to module.linear.0.scores
> <DEBUG> no gradient to module.linear.2.weight
> <DEBUG> gradient to module.linear.2.scores
> <DEBUG> no gradient to module.linear.4.weight
> <DEBUG> gradient to module.linear.4.scores
> => Getting CIFAR10 dataset
> Files already downloaded and verified
> Files already downloaded and verified
>   0%|                                                                                                                                       | 0/391 [00:00<?, ?it/s]torch_shm_manager: error while loading shared libraries: libcudart.so.10.1: cannot open shared object file: No such file or directory
> torch_shm_manager: error while loading shared libraries: libcudart.so.10.1: cannot open shared object file: No such file or directory
> Traceback (most recent call last):
>   File "main.py", line 439, in <module>
>     main()
>   File "main.py", line 44, in main
>     main_worker(args)
>   File "main.py", line 131, in main_worker
>     data.train_loader, model, criterion, optimizer, epoch, args, writer=writer
>   File "/home/xzhoubi/hidden-networks/trainers/default.py", line 31, in train
>     enumerate(train_loader), ascii=True, total=len(train_loader)
>   File "/home/xzhoubi/miniconda3/envs/myenv/lib/python3.7/site-packages/tqdm/std.py", line 1081, in __iter__
>     for obj in iterable:
>   File "/home/xzhoubi/miniconda3/envs/myenv/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 345, in __next__
>     data = self._next_data()
>   File "/home/xzhoubi/miniconda3/envs/myenv/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 856, in _next_data
>     return self._process_data(data)
>   File "/home/xzhoubi/miniconda3/envs/myenv/lib/python3.7/site-packages/torch/utils/data/dataloader.py", line 881, in _process_data
>     data.reraise()
>   File "/home/xzhoubi/miniconda3/envs/myenv/lib/python3.7/site-packages/torch/_utils.py", line 394, in reraise
> torch_shm_manager: error while loading shared libraries: libcudart.so.10.1: cannot open shared object file: No such file or directory
> torch_shm_manager: error while loading shared libraries: libcudart.so.10.1: cannot open shared object file: No such file or directory
>     raise self.exc_type(msg)
> RuntimeError: Caught RuntimeError in DataLoader worker process 0.
> Original Traceback (most recent call last):
>   File "/home/xzhoubi/miniconda3/envs/myenv/lib/python3.7/site-packages/torch/utils/data/_utils/worker.py", line 178, in _worker_loop
>     data = fetcher.fetch(index)
>   File "/home/xzhoubi/miniconda3/envs/myenv/lib/python3.7/site-packages/torch/utils/data/_utils/fetch.py", line 47, in fetch
>     return self.collate_fn(data)
>   File "/home/xzhoubi/miniconda3/envs/myenv/lib/python3.7/site-packages/torch/utils/data/_utils/collate.py", line 79, in default_collate
>     return [default_collate(samples) for samples in transposed]
>   File "/home/xzhoubi/miniconda3/envs/myenv/lib/python3.7/site-packages/torch/utils/data/_utils/collate.py", line 79, in <listcomp>
>     return [default_collate(samples) for samples in transposed]
>   File "/home/xzhoubi/miniconda3/envs/myenv/lib/python3.7/site-packages/torch/utils/data/_utils/collate.py", line 53, in default_collate
>     storage = elem.storage()._new_shared(numel)
>   File "/home/xzhoubi/miniconda3/envs/myenv/lib/python3.7/site-packages/torch/storage.py", line 128, in _new_shared
>     return cls._new_using_filename(size)
> RuntimeError: error executing torch_shm_manager at "/home/xzhoubi/miniconda3/envs/myenv/lib/python3.7/site-packages/torch/bin/torch_shm_manager" at /pytorch/torch/lib/libshm/core.cpp:99
> 
>   0%|

**Comment by mitchellnw** [comment]
Hi, could you try the steps here https://github.com/rusty1s/pytorch_geometric/issues/114

I'm worried that it's something about pytorch and cuda not talking to the same version

**Comment by BorisAnimal** [comment]
I had the same traceback when specified ```num_workers``` parameter in dataloader.  I catch this error all the time on Windows and 50/50 on Linux. The solution I found for me is to set it to 0 (not 1, because this handles different).

**Comment by zhangboshen** [comment]
> I had the same traceback when specified `num_workers` parameter in dataloader. I catch this error all the time on Windows and 50/50 on Linux. The solution I found for me is to set it to 0 (not 1, because this handles different).

Same problem here. I installed cuda10 successfully, but still get the error above, solved by setting num_workers=0. (centOS, pytorch1.4)

**Comment by bairesearch** [comment]
(If using a conda environment) hidden-networks also requires the installation of pytorch-gpu;
`conda install pytorch-gpu`
